export const SINGLE_IMAGE_FILE_MAX_COUNT = 1;
export const ARRAY_IMAGE_FILE_MAX_COUNT = 5;
export const IMAGE_FILE_MAX_SIZE_IN_MB = 10;
export const IMAGE_FILE_MAX_SIZE_IN_BYTES = 1024 * 1024 * IMAGE_FILE_MAX_SIZE_IN_MB;
