export const REDIS_CACHE = 'REDIS_CACHE';

export const REQUIRE_USER_REFRESH = 'REQUIRE_USER_REFRESH';

export const USERS_CACHE_PREFIX = 'USERS';
export const USERS_ALL = `${USERS_CACHE_PREFIX}_ALL`;
export const USERS_LIMIT = `${USERS_CACHE_PREFIX}_LIMIT`;
export const USERS_OFFSET = `${USERS_CACHE_PREFIX}_OFFSET`;
