export const REDIS_CACHE = 'REDIS_CACHE';

export const REVOKE_ACCESS_TOKEN = 'REVOKE_ACCESS_TOKEN'

export const REQUIRE_USER_REFRESH = 'REQUIRE_USER_REFRESH';
export const REVOKE_REFRESH_TOKEN = 'REVOKE_REFRESH_TOKEN';

export const USERS_CACHE_PREFIX = 'USERS';
export const USERS_ALL = `${USERS_CACHE_PREFIX}_ALL`;
export const USERS_LIMIT = `${USERS_CACHE_PREFIX}_LIMIT`;
export const USERS_OFFSET = `${USERS_CACHE_PREFIX}_OFFSET`;

export const PRODUCTS_CACHE_PREFIX = 'PRODUCTS';
export const PRODUCTS_ALL = `${PRODUCTS_CACHE_PREFIX}_ALL`;
export const PRODUCTS_LIMIT = `${PRODUCTS_CACHE_PREFIX}_LIMIT`;
export const PRODUCTS_OFFSET = `${PRODUCTS_CACHE_PREFIX}_OFFSET`;
