export const REDIS_CACHE = 'REDIS_CACHE';

export const REVOKE_ACCESS_TOKEN = 'REVOKE_ACCESS_TOKEN';

export const REQUIRE_USER_REFRESH = 'REQUIRE_USER_REFRESH';
export const REVOKE_REFRESH_TOKEN = 'REVOKE_REFRESH_TOKEN';

export const USERS_CACHE_PREFIX = 'USERS';
export const USERS_ALL = `${USERS_CACHE_PREFIX}_ALL`;
export const USERS_PAGE = `${USERS_CACHE_PREFIX}_PAGE`;
export const USERS_PAGESIZE = `${USERS_CACHE_PREFIX}_PAGESIZE`;

export const PRODUCTS_CACHE_PREFIX = 'PRODUCTS';
export const PRODUCTS_ALL = `${PRODUCTS_CACHE_PREFIX}_ALL`;
export const PRODUCTS_PAGE = `${PRODUCTS_CACHE_PREFIX}_PAGE`;
export const PRODUCTS_PAGESIZE = `${PRODUCTS_CACHE_PREFIX}_PAGESIZE`;
