export const UTILITY_SERVICE = 'UTILITY_SERVICE';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const MAIL_SERVICE = 'MAIL_SERVICE';
export const MANAGEMENTS_SERVICE = 'MANAGEMENTS_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';

export const CLOUDINARY_PROVIDER = 'CLOUDINARY_PROVIDER';
