export const SAMPLE_SERVICE = 'SAMPLE_SERVICE';
export const PRODUCTS_SERVICE = 'PRODUCTS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const MAIL_SERVICE = 'MAIL_SERVICE';
export const MANAGEMENTS_SERVICE = 'MANAGEMENTS_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';

export const CLOUDINARY_PROVIDER = 'CLOUDINARY_PROVIDER';
