version: '3'

services:
    prometheus:
        container_name: prometheus
        hostname: prometheus
        build:
            context: ./containers/prometheus/
            dockerfile: Dockerfile
        environment:
            - STATS_USER="${STATS_USER}"
            - STATS_PASSWORD="${STATS_PASSWORD}"
        ports:
            - 9090
        networks:
            techcell_backend:
        restart: unless-stopped

    grafana:
        container_name: grafana
        hostname: grafana
        build:
            context: ./containers/grafana/
            dockerfile: Dockerfile
        ports:
            - 3000
        volumes:
            - grafana-storage:/var/lib/grafana
        environment:
            - GF_SERVER_HTTP_PORT=3000
            - GF_DATABASE_TYPE=postgres
            - GF_DATABASE_HOST=${POSTGRES_HOST}
            - GF_DATABASE_NAME=${POSTGRES_DB}
            - GF_DATABASE_USER=${POSTGRES_USER}
            - GF_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
            - GF_DATABASE_SSL_MODE=${POSTGRES_SSL_MODE}
        networks:
            techcell_backend:
        restart: unless-stopped

networks:
    techcell_backend:
        driver: bridge

volumes:
    grafana-storage:
