version: '3'

services:
    api:
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
            - /etc/letsencrypt/:/etc/letsencrypt
        ports:
            - 80:8000
            - 443:4430
            - 8000:8000
        networks:
            - techcell_backend
        restart: always

    auth:
        build:
            context: ./
            dockerfile: ./apps/auth/Dockerfile
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        networks:
            - techcell_backend
        restart: always

    mail:
        build:
            context: ./
            dockerfile: ./apps/mail/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        networks:
            - techcell_backend
        restart: always

    products:
        build:
            context: ./
            dockerfile: ./apps/products/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        networks:
            - techcell_backend
        restart: always

    sample:
        build:
            context: ./
            dockerfile: ./apps/sample/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - REDIS_HOST=redis
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        networks:
            - techcell_backend
        restart: always

    managements:
        build:
            context: ./
            dockerfile: ./apps/managements/Dockerfile
        environment:
            - REDIS_HOST=redis
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        networks:
            - techcell_backend
        restart: always

    order:
        build:
            context: ./
            dockerfile: ./apps/order/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        networks:
            - techcell_backend
        restart: always

networks:
    techcell_backend:

volumes:
    app_data:
        driver: local
