version: '3'

services:
    prometheus:
        container_name: prometheus
        hostname: prometheus
        build:
            context: ./containers/prometheus/
            dockerfile: Dockerfile
        environment:
            - STATS_USER="${STATS_USER}"
            - STATS_PASSWORD="${STATS_PASSWORD}"
        ports:
            - 9090
        networks:
            techcell_backend:
        restart: unless-stopped

    grafana:
        container_name: grafana
        hostname: grafana
        build:
            context: ./containers/grafana/
            dockerfile: Dockerfile
        ports:
            - 3000
        volumes:
            - grafana-storage:/var/lib/grafana
        networks:
            techcell_backend:
        restart: unless-stopped

networks:
    techcell_backend:
        driver: bridge

volumes:
    grafana-storage:
