version: '3'

services:
    api:
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - REDIS_HOST=redis
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - redis
            - sample
            - products
            - auth
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
            - /etc/letsencrypt/:/etc/letsencrypt
        ports:
            - 80:8000
            - 443:4430
            - 8000:8000
        command: yarn start:prod api
        networks:
            - backend
        restart: always

    auth:
        build:
            context: ./
            dockerfile: ./apps/auth/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - mongodb-primary
            - mongodb-secondary
            - mongodb-arbiter
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        command: yarn start:prod auth
        networks:
            - backend
        restart: always

    mail:
        build:
            context: ./
            dockerfile: ./apps/mail/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - auth
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        command: yarn start:prod mail
        networks:
            - backend
        restart: always

    products:
        build:
            context: ./
            dockerfile: ./apps/products/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017/techcell-dev?directConnection=true&authMechanism=SCRAM-SHA-1&replicaSet=replicaset&authSource=admin
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - mongodb-primary
            - mongodb-secondary
            - mongodb-arbiter
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        command: yarn start:prod products
        networks:
            - backend
        restart: always

    sample:
        build:
            context: ./
            dockerfile: ./apps/sample/Dockerfile
        environment:
            - RABBITMQ_URLS=amqp://techcell_server:techcell_server_9901@rabbitmq:5672
            - REDIS_HOST=redis
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - .:/usr/src/techcell_app
            - /usr/src/techcell_app/node_modules
        command: yarn start:prod sample
        networks:
            - backend
        restart: always

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        env_file:
            - .env
        volumes:
            - 'rabbitmq_data:/var/lib/rabbitmq'
        networks:
            - backend
        restart: always

    mongodb-primary:
        image: docker.io/bitnami/mongodb:5.0
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_ROOT_PASSWORD=${SET_MONGODB_ROOT_PASSWORD}
            - MONGODB_REPLICA_SET_KEY=${SET_MONGODB_REPLICA_SET_KEY}
        env_file:
            - .env
        volumes:
            - 'mongodb_master_data:/bitnami/mongodb'
        ports:
            - '27027:27017'
        networks:
            - backend
        restart: always

    mongodb-secondary:
        image: docker.io/bitnami/mongodb:5.0
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
            - MONGODB_REPLICA_SET_MODE=secondary
            - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
            - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${SET_MONGODB_ROOT_PASSWORD}
            - MONGODB_REPLICA_SET_KEY=${SET_MONGODB_REPLICA_SET_KEY}
        env_file:
            - .env
        networks:
            - backend
        restart: always

    mongodb-arbiter:
        image: docker.io/bitnami/mongodb:5.0
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
            - MONGODB_REPLICA_SET_MODE=arbiter
            - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
            - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${SET_MONGODB_ROOT_PASSWORD}
            - MONGODB_REPLICA_SET_KEY=${SET_MONGODB_REPLICA_SET_KEY}
        env_file:
            - .env
        networks:
            - backend
        restart: always

    redis:
        image: docker.io/bitnami/redis:7.0
        environment:
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
            - '6379:6379'
        networks:
            - backend
        volumes:
            - 'redis_data:/redis/data'

networks:
    backend:

volumes:
    mongodb_master_data:
        driver: local
    rabbitmq_data:
        driver: local
    app_data:
        driver: local
    redis_data:
        driver: local
