version: "3"

services:
  rabbitmq:
    # image: rabbitmq:3.9.29-management
    image: rabbitmq:3-management
    ports:
      - '5671:5671'
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    networks:
      - backend
  
  # mongodb:
  #   image: mongo:4.4
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: master123
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - backend

networks:
  backend:

volumes:
  # mongo_data:
  rabbitmq_data:
    driver: local
