version: '3'

services:
    compodoc-techcell:
        container_name: compodoc-techcell
        hostname: compodoc-techcell
        build:
            context: ./
            dockerfile: ./containers/compodoc-techcell/Dockerfile
        image: lehuygiang28/compodoc-techcell:${COMPOSE_TAG:-latest}
        ports:
            - 9001:${COMPODOC_PORT:-9001}
        networks:
            - techcell_backend
        restart: unless-stopped

    api:
        container_name: api
        hostname: api
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        image: lehuygiang28/techcell_api:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        ports:
            - 8000:${API_PORT:-8000}
        networks:
            - techcell_backend
        restart: unless-stopped

    auth:
        container_name: auth
        hostname: auth
        build:
            context: ./
            dockerfile: ./apps/auth/Dockerfile
        image: lehuygiang28/techcell_auth:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        networks:
            - techcell_backend
        restart: unless-stopped

    communications:
        container_name: communications
        hostname: communications
        build:
            context: ./
            dockerfile: ./apps/communications/Dockerfile
        image: lehuygiang28/techcell_communications:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        ports:
            - 8001:${COMMUNICATIONS_PORT:-8001}
        networks:
            - techcell_backend
        restart: unless-stopped

    search:
        container_name: search
        hostname: search
        build:
            context: ./
            dockerfile: ./apps/search/Dockerfile
        image: lehuygiang28/techcell_search:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        networks:
            - techcell_backend
        restart: unless-stopped

    utility:
        container_name: utility
        hostname: utility
        build:
            context: ./
            dockerfile: ./apps/utility/Dockerfile
        image: lehuygiang28/techcell_utility:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        networks:
            - techcell_backend
        restart: unless-stopped

    managements:
        container_name: managements
        hostname: managements
        build:
            context: ./
            dockerfile: ./apps/managements/Dockerfile
        image: lehuygiang28/techcell_managements:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        networks:
            - techcell_backend
        restart: unless-stopped

    order:
        container_name: order
        hostname: order
        build:
            context: ./
            dockerfile: ./apps/order/Dockerfile
        image: lehuygiang28/techcell_order:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        networks:
            - techcell_backend
        restart: unless-stopped

    task:
        container_name: task
        hostname: task
        build:
            context: ./
            dockerfile: ./apps/task/Dockerfile
        image: lehuygiang28/techcell_task:${COMPOSE_TAG:-latest}
        env_file:
            - .env
        networks:
            - techcell_backend
        restart: unless-stopped

networks:
    techcell_backend:
        driver: bridge
