version: '3'

services:
    prometheus:
        container_name: prometheus
        hostname: prometheus
        build:
            context: ./containers/prometheus/
            dockerfile: Dockerfile
        environment:
            - STATS_USER=${STATS_USER}
            - STATS_PASSWORD=${STATS_PASSWORD}
        ports:
            - ${PROMETHEUS_PORT:-9090}
        networks:
            techcell_backend:
        restart: unless-stopped

    grafana:
        container_name: grafana
        hostname: grafana
        build:
            context: ./containers/grafana/
            dockerfile: Dockerfile
        ports:
            - ${GRAFANA_PORT:-9091}
        volumes:
            - grafana-storage:/var/lib/grafana
        environment:
            - GF_SERVER_HTTP_PORT=${GRAFANA_PORT:-9091}
            - GF_DATABASE_TYPE=${GRAFANA_DATABASE_TYPE:-sqlite3}
        networks:
            techcell_backend:
        restart: unless-stopped

    node_exporter:
        container_name: node_exporter
        hostname: node_exporter
        build:
            context: ./containers/node_exporter/
            dockerfile: Dockerfile
        ports:
            - ${GRAFANA_NODE_EXPORTER:-9092}
        volumes:
            - proc_volume:/host/proc:ro
            - sys_volume:/host/sys:ro
            - rootfs_volume:/rootfs:ro
        networks:
            - techcell_backend
        restart: unless-stopped

networks:
    techcell_backend:
        driver: bridge

volumes:
    grafana-storage:
    proc_volume:
    sys_volume:
    rootfs_volume:
