version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    external: true
    name: infrastructure


volumes:
  mongo_data:
    driver: local