export const REVOKE_ACCESS_TOKEN = 'REVOKE_ACCESS_TOKEN';

export const REQUIRE_USER_REFRESH = 'REQUIRE_USER_REFRESH';
export const REVOKE_REFRESH_TOKEN = 'REVOKE_REFRESH_TOKEN';

export const USERS_CACHE_PREFIX = 'USERS';
export const USERS_ALL = `${USERS_CACHE_PREFIX}_ALL`;
export const USERS_PAGE = `${USERS_CACHE_PREFIX}_PAGE`;
export const USERS_PAGESIZE = `${USERS_CACHE_PREFIX}_PAGESIZE`;

export const PRODUCTS_CACHE_PREFIX = 'PRODUCTS';
export const PRODUCTS_ALL = `${PRODUCTS_CACHE_PREFIX}_ALL`;
export const PRODUCTS_PAGE = `${PRODUCTS_CACHE_PREFIX}_PAGE`;
export const PRODUCTS_PAGESIZE = `${PRODUCTS_CACHE_PREFIX}_PAGESIZE`;

export const REVENUE_IN_MONTH_CACHE_PREFIX = 'REVENUE_IN_MONTH';
export const REVENUE_IN_WEEK_CACHE_PREFIX = 'REVENUE_IN_WEEK';
export const REVENUE_CHART_CACHE_PREFIX = 'REVENUE_CHART';

export const STATS_CACHE_PREFIX = 'CACHE_STATS';
export const REVENUE_YEAR = `${STATS_CACHE_PREFIX}_REVENUE_YEAR`;
export const REVENUE_MONTH = `${STATS_CACHE_PREFIX}_REVENUE_MONTH`;
export const REVENUE_DAY = `${STATS_CACHE_PREFIX}_REVENUE_DAY`;
export const REVENUE_HOUR = `${STATS_CACHE_PREFIX}_REVENUE_HOUR`;
