export const UTILITY_SERVICE = 'UTILITY_SERVICE';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const COMMUNICATIONS_SERVICE = 'COMMUNICATIONS_SERVICE';
export const MANAGEMENTS_SERVICE = 'MANAGEMENTS_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const TASK_SERVICE = 'TASK_SERVICE';

export const CLOUDINARY_PROVIDER = 'CLOUDINARY_PROVIDER';
