name: Auto Merge Development Branch

on:
    schedule:
        - cron: '0 0 * * 1'
    workflow_dispatch:

jobs:
    create_pull_request:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Create pull request
              run: |
                  title="Automatic PR: Merging development into stable ($(git rev-parse --short=7 remotes/origin/development))"

                  body="
                  This pull request was automatically created by GitHub Actions, and it is automatically done at the start of every Monday or manually ran. It merges all of the changes that were made to the \`development\` branch into the \`stable\` branch.

                  The reason why the [\`development\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/development) branch exists is to make sure that all of the code in [\`stable\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/stable) has been properly reviewed and approved. **Some contributors** have to approve this pull request for it to be merged.
                      
                  **Last commit to [\`development\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/development):** https://github.com/TechCell-Project/tech-cell-web-server/commit/$(git rev-parse remotes/origin/development)
                  "

                  gitLog=$(git log remotes/origin/stable..remotes/origin/development)

                  if [ -n "$gitLog" ]; then
                      gh pr create -B "stable" -H "development" --title "$title" -l "auto-pr" --body "$body"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
