name: Build all Nest services

on:
  push:
    branches: [stable, development]
  pull_request:
    branches: ["*"]

jobs:
  select-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          # This script checks if the pull request has the label "run-ubuntu-latest" and if so, runs the job on ubuntu-latest.
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            labels=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "${{ github.event.pull_request.url }}/labels")
            if echo "$labels" | jq -e '.[] | select(.name == "run-ubuntu-latest")' > /dev/null; then
              echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
              exit 0
            elif echo "$labels" | jq -e '.[] | select(.name == "run-self-hosted")' > /dev/null; then
              echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi

          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  build:
    needs: select-runner
    runs-on: ${{ needs.select-runner.outputs.runner-label }}

    steps:
      - name: Log runner label
        run: echo "Running on runner ${{ needs.select-runner.outputs.runner-label }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build services
        run: yarn build:all
