name: Build all Nest services

on:
  push:
    branches: [stable, development]
  pull_request:
    branches: ["*"]

jobs:
  select-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        uses: ./.github/includes/select-runner.yml

  build:
    needs: select-runner
    runs-on: ${{ needs.select-runner.outputs.runner-label }}

    steps:
      - name: Log runner label
        run: echo "Running on runner ${{ needs.select-runner.outputs.runner-label }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build services
        run: yarn build:all
