name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - development
      - test-action

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  COMPOSE_PROJECT_NAME: tech-cell-server
  CURRENT_USER: 0:0
  DOCKER_GROUP: 0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for no_push_docker label
        id: check-label
        uses: actions/github-script@v4
        with:
          script: |
            const labels = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const hasNoPushDockerLabel = labels.data.some(label => label.name === 'no_push_docker');
            console.log(`Has no_push_docker label: ${hasNoPushDockerLabel}`);
            return { hasNoPushDockerLabel: hasNoPushDockerLabel }

      - name: Skip build and push if no_push_docker label is present
        if: steps.check-label.outputs.hasNoPushDockerLabel == true
        run: echo "Skipping build and push because no_push_docker label is present"

      - name: Login to Docker Hub
        if: steps.check-label.outputs.hasNoPushDockerLabel != true
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
          
      - name: 'Create .env file'
        if: steps.check-label.outputs.hasNoPushDockerLabel != true
        run: |
          touch .env
          echo COMPOSE_PROJECT_NAME= ${{ env.COMPOSE_PROJECT_NAME }} >> .env
          echo CURRENT_USER= ${{ env.CURRENT_USER }} >> .env
          echo DOCKER_GROUP= ${{ env.DOCKER_GROUP }} >> .env
          cat .env

      - name: Build and push images
        if: steps.check-label.outputs.hasNoPushDockerLabel != true
        run: |
          docker-compose -f docker-compose.prod.yml build --no-cache
          docker-compose -f docker-compose.prod.yml push

      - name: Remove .env file
        if: steps.check-label.outputs.hasNoPushDockerLabel != true
        run: |
          rm .env

