name: Build docker image for testing

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    COMPOSE_PROJECT_NAME: tech-cell-server

jobs:
    build-and-push-to-dockerhub:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.DOCKERHUB_USERNAME }}
                  password: ${{ env.DOCKERHUB_PASSWORD }}

            - name: Free disk space up
              run: rm -rf /opt/hostedtoolcache

            - name: Set short SHA
              id: set_short_sha
              run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT

            - name: 'Create .env file'
              run: |
                  touch .env
                  echo COMPOSE_PROJECT_NAME= ${{ env.COMPOSE_PROJECT_NAME }} >> .env
                  echo COMPOSE_TAG= "${{ steps.set_short_sha.outputs.SHORT_SHA }}" >> .env
                  cat .env

            - name: Build images
              id: build
              run: |
                  docker compose -f docker-compose.prod.yml build
                  docker images

            - name: Overwrite .env file for latest tag
              run: |
                  echo COMPOSE_TAG= "latest" >> .env
                  cat .env

            - name: Buildvimages with latest tag
              id: build_latest
              run: |
                  docker compose -f docker-compose.prod.yml build
                  docker images

            - name: Remove .env file
              run: |
                  rm .env
