name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - development
      - test-action

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  COMPOSE_PROJECT_NAME: tech-cell-server
  CURRENT_USER: 0:0
  DOCKER_GROUP: 0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for no_push_docker label
        id: check-label
        run: |
          gh issue view ${{ github.event.issue.number }} --json labels --jq '.labels[].name' > labels.txt
          if grep -q no_push_docker labels.txt; then
            echo "Skipping build and push because no_push_docker label is present"
            exit 0
          fi

      - name: Login to Docker Hub
        if: steps.check-label.outputs.hasNoPushDockerLabel != true
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
          
      - name: 'Create .env file'
        run: |
          touch .env
          echo COMPOSE_PROJECT_NAME= ${{ env.COMPOSE_PROJECT_NAME }} >> .env
          echo CURRENT_USER= ${{ env.CURRENT_USER }} >> .env
          echo DOCKER_GROUP= ${{ env.DOCKER_GROUP }} >> .env
          cat .env

      - name: Build and push images
        run: |
          docker-compose -f docker-compose.prod.yml build --no-cache
          docker-compose -f docker-compose.prod.yml push

      - name: Remove .env file
        run: |
          rm .env