name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - development
      - test-action

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  COMPOSE_PROJECT_NAME: tech-cell-server
  CURRENT_USER: 0:0
  DOCKER_GROUP: 0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: "!contains(github.event.issue.labels.*.name, 'no_push_docker')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get issue number
        id: get-issue-number
        run: echo "::set-output name=issue_number::$(gh issue view --json number | jq -r '.')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push images
        run: docker-compose -f docker-compose.prod.yml build --no-cache && docker-compose -f docker-compose.prod.yml push