name: Pull Request Filter

on: pull_request_target

jobs:
    filter:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Label pull request
              uses: actions/labeler@v4

            - name: Close pull requests that directly commit to stable
              run: |
                  comment="
                  You can not directly commit to the [\`stable\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/stable) branch, read the [contribution guide](https://github.com/TechCell-Project/.git-docs#-l%C6%B0u-%C3%BD) and only commit to [\`development\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/development).
                  "

                  exclude_labels="
                  bypass
                  auto-pr
                  "

                  no_run=false

                  for pr_number in $(gh pr list --json number --jq '.[].number'); do
                      echo "Processing pull request: #$pr_number"
                      
                      for label in $(gh pr view $pr_number --json labels --jq '.labels[].name'); do
                          if [[ "$exclude_labels" == *"$label"* ]]; then
                              no_run=true
                              break
                          fi
                      done
                      
                      if [ "$no_run" == "true" ]; then
                          echo "Pull request #$pr_number merges into stable, but it is being bypassed due to its labels."
                      else
                          if [ $(gh pr view $pr_number --json baseRefName --jq '.baseRefName') == 'stable' ]; then
                              echo "Closing pull request #$pr_number as it directly commits to stable..."
                              gh pr label $pr_number --add auto-close actions
                              gh pr close $pr_number --comment "$comment"
                          fi
                      fi
                  done
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
