name: Pull Request Filter

on:
    pull_request:
        types: [opened]

jobs:
    filter:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Label pull request
              uses: actions/labeler@v4

            - name: Close pull requests that directly commit to stable
              run: |
                  set -euo pipefail
                  exec 2>&1
                  comment="
                  You can not directly commit to the [\`stable\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/stable) branch, read the [contribution guide](https://github.com/TechCell-Project/.git-docs#-l%C6%B0u-%C3%BD) and only commit to [\`development\`](https://github.com/TechCell-Project/tech-cell-web-server/tree/development).
                  "
                  exclude_labels="bypass|auto-pr"
                  for pr_number in $(gh pr list --json number --jq '.[].number'); do
                    echo "Processing pull request: #$pr_number"
                    if gh pr view $pr_number --json labels[].name | grep -q -E '(^|\s)'"$(echo "$exclude_labels" | sed 's/\n/\\\\s|/g')"'($|\s)'; then
                      echo "Pull request #$pr_number merges into stable, but it is being bypassed due to its labels."
                    elif [ $(gh pr view $pr_number --json baseRefName --jq '.baseRefName') = "stable" ]; then
                      echo "Closing pull request #$pr_number as it directly commits to stable..."
                      gh pr close $pr_number --comment "$comment"
                    fi
                  done
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
