name: Generate SDK

on:
    push:
        branches:
            - development
    pull_request:
        branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@lehuygiang28'

            - name: 'Create .env file'
              run: |
                  touch .env
                  echo GOOGLE_CLIENT_ID= 'google_sample' >> .env
                  echo GOOGLE_CLIENT_SECRET= 'google_sample' >> .env
                  echo GOOGLE_REDIRECT_URL= 'google_sample' >> .env
                  echo JWT_ACCESS_TOKEN_SECRET= 'jwt_sample' >> .env
                  echo JWT_REFRESH_TOKEN_SECRET= 'jwt_sample' >> .env
                  echo JWT_ACCESS_TOKEN_EXPIRE_TIME_STRING= '1h' >> .env
                  echo JWT_REFRESH_TOKEN_EXPIRE_TIME_STRING= '1h' >> .env
                  echo FALLBACK_LANGUAGE= 'en' >> .env
                  echo RABBITMQ_UTILITY_QUEUE= 'utility_queue' >> .env
                  echo RABBITMQ_SEARCH_QUEUE= 'search_queue' >> .env
                  echo RABBITMQ_AUTH_QUEUE= 'auth_queue' >> .env
                  echo RABBITMQ_COMMUNICATIONS_QUEUE= 'communications_queue' >> .env
                  echo RABBITMQ_MANAGEMENTS_QUEUE= 'managements_queue' >> .env
                  echo RABBITMQ_ORDER_QUEUE= 'order_queue' >> .env
                  echo RABBITMQ_TASK_QUEUE= 'task_queue' >> .env
                  echo MONGODB_URI= '${{secrets.MONGODB_URI}}' >> .env
                  echo RABBITMQ_URLS= '${{secrets.RABBITMQ_URLS}}' >> .env
                  echo REDIS_HOST= '${{secrets.REDIS_HOST}}' >> .env
                  echo REDIS_PORT= '${{secrets.REDIS_PORT}}' >> .env
                  echo REDIS_PASSWORD= '${{secrets.REDIS_PASSWORD}}' >> .env
                  cat .env

            - name: Install dependencies
              run: yarn install

            - name: Run the web server and generate the OpenAPI YAML
              run: |
                  yarn start:dev api &
                  sleep 15 &&
                  curl http://localhost:8000 &&
                  yarn generate:swagger-yaml

            - name: Download Swagger Codegen Generator
              run: |
                  wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.51/swagger-codegen-cli-3.0.51.jar -O swagger-codegen-cli.jar
                  java -jar swagger-codegen-cli.jar --help

            - name: Generate SDK
              run: |
                  java -jar swagger-codegen-cli.jar generate \
                  -i swagger.yaml \
                  -l javascript \
                  --git-user-id "lehuygiang28" \
                  --git-repo-id "tech-cell-server-node-sdk" \
                  --release-note "Github integration generated" \
                  -o ./generated/javascript

            - name: Update package.json
              run: |
                  echo Adding publishConfig, updating name and version in package.json...
                  techcell_version=$(node -p "require('./package.json').version")
                  commit_hash=$(git rev-parse --short HEAD)
                  node -e "let pkg=require('./generated/javascript/package.json'); pkg.name='@lehuygiang28/tech-cell-server-node-sdk'; pkg.version='${techcell_version}-${commit_hash}'; pkg.publishConfig={registry:'https://npm.pkg.github.com/'}; pkg.author='Lê Huy Giang <lehuygiang28@gmail.com>'; require('fs').writeFileSync('./generated/javascript/package.json', JSON.stringify(pkg, null, 2));"

            - name: Push to GitHub
              run: |
                  cd ./generated/javascript
                  git config --global user.email "lehuygiang28@gmail.com"
                  git config --global user.name "lehuygiang28"
                  /bin/sh ./git_push.sh
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  GIT_TOKEN: ${{secrets.GIAANG_SDK_REPO_SECRET}}

            - name: Publish to GitHub Packages
              run: |
                  cd ./generated/javascript
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GIAANG_PACKAGE_TOKEN}}
